name: "movielens_session_filter"
backend: "python"
input {
  name: "candidate_movie_ids"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
input {
  name: "session_movie_ids"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
output {
  name: "filtered_movie_ids"
  data_type: TYPE_INT32
  dims: -1
  dims: 1  
}