name: "movielens_retrieval_tf"
backend: "tensorflow"
platform: "tensorflow_savedmodel"
input {
  name: "movie_id_count"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
input {
  name: "movie_ids__values"
  data_type: TYPE_INT64
  dims: -1
  dims: 1
}
input {
  name: "movie_ids__nnzs"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
input {
  name: "genres__values"
  data_type: TYPE_INT64
  dims: -1
  dims: 1
}
input {
  name: "genres__nnzs"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
input {
  name: "search_terms__values"
  data_type: TYPE_INT64
  dims: -1
  dims: 1
}
input {
  name: "search_terms__nnzs"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
output {
  name: "output_1"
  data_type: TYPE_FP32
  dims: -1
  dims: 128
}

