# Copyright (c) 2021, NVIDIA CORPORATION.

# Usage:
#   conda build . -c defaults -c conda-forge -c numba -c rapidsai

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.1').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% set py_version=environ.get('CONDA_PY', 36) %}
{% set setup_py_data = load_setup_py_data() %}

package:
  name: nvtabular
  version: {{ version }}

source:
  path: ../../

build:
  number: {{ git_revision_count }}
  script: python -m pip install . -vvv


requirements:
  build:
    - python
    - setuptools
    - pybind11>=2.7.0
    - protobuf>=3.0.0
  run:
  {% for req in setup_py_data.get('install_requires', []) %}
    - {{ req }}
  {% endfor %}
    - python
    - cudf>=21.10.*
    - dask-cudf>=21.10.*
    - cupy>=7.2.0,<10.0.0a
    - nvtx>=0.2.1
    - pynvml

about:
  home: https://github.com/NVIDIA/NVTabular
  license_file: LICENSE
  summary: NVTabular library
