# Copyright (c) 2020, NVIDIA CORPORATION.

# Usage:
#   conda build . -c defaults -c conda-forge -c numba -c rapidsai

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.1').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set git_revision_count=environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% set cuda_version='.'.join(environ.get('CUDA', 'unknown').split('.')[:2]) %}
{% set py_version=environ.get('CONDA_PY', 36) %}

package:
  name: nvtabular
  version: {{ version }}

source:
  path: ../../

build:
  number: {{ git_revision_count }}
  string: {{ git_revision_count }}
  noarch: python

requirements:
  build:
    - python x.x
    - setuptools
    - cudf 0.15.*
  run:
    - python x.x
    - cudf 0.15.*
    - dask-cudf 0.15.*
    - cupy>=7.2.0,<9.0.0a
    - dask>=2.12.0
    - distributed>=2.12.0
    - PyYAML>=5.3
    - nvtx>=0.2.1

about:
  home: https://github.com/NVIDIA/NVTabular
  license: Apache-2.0
  # license_file: LICENSE
  summary: NVTabular library
