name: "movielens_ranking_tf"
backend: "tensorflow"
platform: "tensorflow_savedmodel"
input {
  name: "movie_genres_1"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
input {
  name: "movie_genres_2"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
input {
  name: "movie_id"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
input {
  name: "movie_tags_nunique"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
input {
  name: "movie_tags_unique_1"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
input {
  name: "movie_tags_unique_2"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
input {
  name: "user_genres_1"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
input {
  name: "user_genres_2"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
input {
  name: "user_movie_id_count"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
input {
  name: "user_movie_ids_1"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
input {
  name: "user_movie_ids_2"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
input {
  name: "user_search_terms_1"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
input {
  name: "user_search_terms_2"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
output {
  name: "output_1"
  data_type: TYPE_FP32
  dims: -1
  dims: 1
}
