name: "ensemble_model"
platform: "ensemble"
input {
  name: "user_id"
  data_type: TYPE_INT32
  dims: -1
  dims: -1
}
output {
  name: "candidate_ids"
  data_type: TYPE_INT32
  dims: -1
  dims: -1
}
ensemble_scheduling {
  step {
    model_name: "0_queryfeast"
    model_version: -1
    input_map {
      key: "user_id"
      value: "user_id"
    }
    output_map {
      key: "genres_1"
      value: "genres_1_0"
    }
    output_map {
      key: "genres_2"
      value: "genres_2_0"
    }
    output_map {
      key: "movie_id_count"
      value: "movie_id_count_0"
    }
    output_map {
      key: "movie_ids_1"
      value: "movie_ids_1_0"
    }
    output_map {
      key: "movie_ids_2"
      value: "movie_ids_2_0"
    }
    output_map {
      key: "search_terms_1"
      value: "search_terms_1_0"
    }
    output_map {
      key: "search_terms_2"
      value: "search_terms_2_0"
    }
  }
  step {
    model_name: "1_predicttensorflow"
    model_version: -1
    input_map {
      key: "genres_1"
      value: "genres_1_0"
    }
    input_map {
      key: "genres_2"
      value: "genres_2_0"
    }
    input_map {
      key: "movie_id_count"
      value: "movie_id_count_0"
    }
    input_map {
      key: "movie_ids_1"
      value: "movie_ids_1_0"
    }
    input_map {
      key: "movie_ids_2"
      value: "movie_ids_2_0"
    }
    input_map {
      key: "search_terms_1"
      value: "search_terms_1_0"
    }
    input_map {
      key: "search_terms_2"
      value: "search_terms_2_0"
    }
    output_map {
      key: "output_1"
      value: "output_1_1"
    }
  }
  step {
    model_name: "2_queryfaiss"
    model_version: -1
    input_map {
      key: "output_1"
      value: "output_1_1"
    }
    output_map {
      key: "candidate_ids"
      value: "candidate_ids"
    }
  }
}
