name: "movielens"
platform: "ensemble"
input {
  name: "user_id"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
output {
  name: "filtered_candidate_ids"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
output {
  name: "predicted_scores"
  data_type: TYPE_FP32
  dims: -1
  dims: 1
}
output {
  name: "ordered_movie_ids"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
ensemble_scheduling {
  step {
    model_name: "movielens_user_features"
    model_version: -1
    input_map {
      key: "user_id"
      value: "user_id"
    }
    output_map {
      key: "movie_id_count"
      value: "movie_id_count_uf"
    }
    output_map {
      key: "movie_ids__values"
      value: "movie_ids_values_uf"
    }
    output_map {
      key: "movie_ids__nnzs"
      value: "movie_ids_nnzs_uf"
    }
    output_map {
      key: "genres__values"
      value: "genres_values_uf"
    }
    output_map {
      key: "genres__nnzs"
      value: "genres_nnzs_uf"
    }
    output_map {
      key: "search_terms__values"
      value: "search_terms_values_uf"
    }
    output_map {
      key: "search_terms__nnzs"
      value: "search_terms_nnzs_uf"
    }
  }
  step {
    model_name: "movielens_retrieval_tf"
    model_version: -1
    input_map {
      key: "movie_id_count"
      value: "movie_id_count_uf"
    }
    input_map {
      key: "movie_ids_1"
      value: "movie_ids_values_uf"
    }
    input_map {
      key: "movie_ids_2"
      value: "movie_ids_nnzs_uf"
    }
    input_map {
      key: "genres_1"
      value: "genres_values_uf"
    }
    input_map {
      key: "genres_2"
      value: "genres_nnzs_uf"
    }
    input_map {
      key: "search_terms_1"
      value: "search_terms_values_uf"
    }
    input_map {
      key: "search_terms_2"
      value: "search_terms_nnzs_uf"
    }
    output_map {
      key: "output_1"
      value: "user_vector"
    }
  }
  step {
    model_name: "movielens_item_ann"
    model_version: -1
    input_map {
      key: "user_vector"
      value: "user_vector"
    }
    output_map {
      key: "candidate_ids"
      value: "candidate_ids"
    }
    # output_map {
    #   key: "candidate_distances"
    #   value: "candidate_distances"
    # }
  }
  step {
    model_name: "movielens_session_filter"
    model_version: -1
    input_map {
      key: "candidate_movie_ids"
      value: "candidate_ids"
    }
    input_map {
      key: "session_movie_ids"
      value: "movie_ids_values_uf"
    }
    output_map {
      key: "filtered_movie_ids"
      value: "filtered_candidate_ids"
    }
  }
  step {
    model_name: "movielens_item_features"
    model_version: -1
    input_map {
      key: "movie_id"
      value: "filtered_candidate_ids"
    }
    output_map {
      key: "genres__values"
      value: "movie_genres_values_if"
    }
    output_map {
      key: "genres__nnzs"
      value: "movie_genres_nnzs_if"
    }
    output_map {
      key: "tags_nunique"
      value: "movie_tags_nunique_if"
    }
    output_map {
      key: "tags_unique__values"
      value: "movie_tags_unique_values_if"
    }
    output_map {
      key: "tags_unique__nnzs"
      value: "movie_tags_unique_nnzs_if"
    }
  }
  step {
    model_name: "movielens_user_unroll"
    model_version: -1
    input_map {
      key: "candidate_movie_ids"
      value: "filtered_candidate_ids"
    }
    input_map {
      key: "movie_id_count"
      value: "movie_id_count_uf"
    }
    input_map {
      key: "movie_ids__values"
      value: "movie_ids_values_uf"
    }
    input_map {
      key: "movie_ids__nnzs"
      value: "movie_ids_nnzs_uf"
    }
    input_map {
      key: "genres__values"
      value: "genres_values_uf"
    }
    input_map {
      key: "genres__nnzs"
      value: "genres_nnzs_uf"
    }
    input_map {
      key: "search_terms__values"
      value: "search_terms_values_uf"
    }
    input_map {
      key: "search_terms__nnzs"
      value: "search_terms_nnzs_uf"
    }
    output_map {
      key: "movie_id_count_ur"
      value: "movie_id_count_ur"
    }
    output_map {
      key: "movie_ids_values_ur"
      value: "movie_ids_values_ur"
    }
    output_map {
      key: "movie_ids_nnzs_ur"
      value: "movie_ids_nnzs_ur"
    }
    output_map {
      key: "genres_values_ur"
      value: "genres_values_ur"
    }
    output_map {
      key: "genres_nnzs_ur"
      value: "genres_nnzs_ur"
    }
    output_map {
      key: "search_terms_values_ur"
      value: "search_terms_values_ur"
    }
    output_map {
      key: "search_terms_nnzs_ur"
      value: "search_terms_nnzs_ur"
    }
  }
  step {
    model_name: "movielens_ranking_tf"
    model_version: -1
    input_map {
      key: "movie_id"
      value: "filtered_candidate_ids"
    }
    input_map {
      key: "movie_genres_1"
      value: "movie_genres_values_if"
    }
    input_map {
      key: "movie_genres_2"
      value: "movie_genres_nnzs_if"
    }
    input_map {
      key: "movie_tags_nunique"
      value: "movie_tags_nunique_if"
    }
    input_map {
      key: "movie_tags_unique_1"
      value: "movie_tags_unique_values_if"
    }
    input_map {
      key: "movie_tags_unique_2"
      value: "movie_tags_unique_nnzs_if"
    }
    input_map {
      key: "user_movie_id_count"
      value: "movie_id_count_ur"
    }
    input_map {
      key: "user_movie_ids_1"
      value: "movie_ids_values_ur"
    }
    input_map {
      key: "user_movie_ids_2"
      value: "movie_ids_nnzs_ur"
    }
    input_map {
      key: "user_genres_1"
      value: "genres_values_ur"
    }
    input_map {
      key: "user_genres_2"
      value: "genres_nnzs_ur"
    }
    input_map {
      key: "user_search_terms_1"
      value: "search_terms_values_ur"
    }
    input_map {
      key: "user_search_terms_2"
      value: "search_terms_nnzs_ur"
    }
    output_map {
      key: "output_1"
      value: "predicted_scores"
    }
  }
  step {
    model_name: "movielens_order_policy"
    model_version: -1
    input_map {
      key: "candidate_movie_ids"
      value: "filtered_candidate_ids"
    }
    input_map {
      key: "predicted_scores"
      value: "predicted_scores"
    }
    output_map {
      key: "ordered_ids"
      value: "ordered_movie_ids"
    }
  }
}
