name: Test conda env creation

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 14 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        default: 'warning'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        target: ["11.0", "11.2"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Create Conda environment with CUDA ${{ matrix.target }}
      run: |
        conda env create --file conda/environments/nvtabular_dev_cuda${{ matrix.target }}.yml --name nvtabular_dev_cuda${{ matrix.target }}
