name: Test Conda environments

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 14 * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Create Conda environment with CUDA 10.1
      run: |
        conda env create --file environment.yml --name nvtabular_dev_10.1
    - name: Create Conda environment with CUDA 10.2
      run: |
        conda env create --file environment.yml --name nvtabular_dev_10.2
    - name: Create Conda environment with CUDA 11.0
      run: |
        conda env create --file environment.yml --name nvtabular_dev_11.0
