name: Test CUDA 10.2 conda env

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 14 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Create Conda environment with CUDA 10.2
      run: |
        conda env create --file conda/environments/nvtabular_dev_cuda10.2.yml --name nvtabular_dev_10.2
