name: "movielens_order_policy"
backend: "python"
input {
  name: "candidate_movie_ids"
  data_type: TYPE_INT32
  dims: -1
  dims: 1
}
input {
  name: "predicted_scores"
  data_type: TYPE_FP32
  dims: -1
  dims: 1
}
output {
  name: "ordered_ids"
  data_type: TYPE_INT32
  dims: -1
  dims: 1  
}